### ISSUE TITLE
file command not found

### ISSUE THREAD

**Issue by ChrisMcKenzie** [wercker/step-github-upload-asset#1]
the golang:1.5-wheezy container on the docker registry does not have the `file` command used to check mime-type and causes the step to fail. Is there a possibility of adding another check for this and use an alternative?

current the solution is to manually set mime-type

**Comment by hatchan** [comment]
I think using `file` is one of the lowest denominators for content type matching.

Most likely you're not going to change the type of the file that often, so manually setting this is probably fine. 

If you come across any portable solutions, PR's are welcome.
