### ISSUE TITLE
No 'file' command in google/golang image

### ISSUE THREAD

**Issue by lukaszraczylo** [wercker/step-github-upload-asset#2]
This line https://github.com/wercker/step-github-upload-asset/blob/master/run.sh#L77 throws an error during build / deploy process

```
/pipeline/github-upload-asset-e388270b-f6d2-4f0b-92d6-f065472f1db9/run.sh: line 77: file: command not found
```

**Comment by hatchan** [comment]
The file command is not installed on all containers. There are two
solutions:

- install `file` on the container
- specify the content type by using the `content-type` (see options in
readme)

**Comment by lukaszraczylo** [comment]
@hatchan thank you for quick response! Would you mind if i'd leave this issue opened for others to avoid duplication ( like with #1 ) ?

**Comment by hatchan** [comment]
I've just updated the README to include a section about this issue. So (hopefully) there's no need to keep this open.
